---
name: DBIx-Migration-Directories
version: 0.11
author:
  - 'Tyler "Crackerjack" MacDonald <japh@crackerjack.net>'
abstract: Install/remove/upgrade/downgrade SQL schemas
license: perl
requires:
  DBI: 1.41
  DBIx::Transaction: 0.005
  File::Basename::Object: 0.01
  Pod::Usage: 1
build_requires:
  Data::Dumper: 2.10
  Module::Build: 0.27_03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  DBIx::Migration::Directories:
    file: lib/DBIx/Migration/Directories.pm
    version: 0.11
  DBIx::Migration::Directories::Base:
    file: lib/DBIx/Migration/Directories/Base.pm
  DBIx::Migration::Directories::Build:
    file: lib/DBIx/Migration/Directories/Build.pm
  DBIx::Migration::Directories::Build::Base:
    file: lib/DBIx/Migration/Directories/Build/Base.pm
  DBIx::Migration::Directories::Database:
    file: lib/DBIx/Migration/Directories/Database.pm
  DBIx::Migration::Directories::Database::SQLite2:
    file: lib/DBIx/Migration/Directories/Database/SQLite2.pm
  DBIx::Migration::Directories::Database::mysql:
    file: lib/DBIx/Migration/Directories/Database/mysql.pm
  DBIx::Migration::Directories::Test:
    file: lib/DBIx/Migration/Directories/Test.pm
resources:
  license: http://dev.perl.org/licenses/
